import 'package:calories_fix/core/constants/app_images.dart';
import 'package:calories_fix/l10n/app_localizations.dart';
import 'package:calories_fix/models/food_model.dart';
import 'package:flutter/material.dart';

class MealsLists {
  MealsLists._();

  static List<FoodModel> breakfastMeals(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return [
      FoodModel(
        id: 'BR1',
        name: l10n.chiaPuddingName,
        imagePath: Assets.assetsImagesBr1,
        weight: l10n.g150,
        calories: 300,
        protein: 11,
        carbs: 33,
        fat: 13,
        ingredients: l10n.chiaPuddingIngredients,
        price: 100,
      ),
      FoodModel(
        id: '2',
        name: l10n.pancakesName,
        imagePath: Assets.assetsImagesBr2,
        weight: l10n.g150,
        calories: 354,
        protein: 35,
        carbs: 26,
        fat: 13,
        ingredients: l10n.pancakesIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'BR3',
        name: l10n.eggRollName,
        imagePath: Assets.assetsImagesBr3,
        weight: l10n.saladWeight, // لو محتاج تترجم 'salad'
        calories: 420,
        protein: 21,
        carbs: 16,
        fat: 26,
        ingredients: l10n.eggRollIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'BR4',
        name: l10n.croissantName,
        imagePath: Assets.assetsImagesBr4,
        weight: '',
        calories: 405,
        protein: 22,
        carbs: 26,
        fat: 18,
        ingredients: l10n.croissantIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'BR5',
        name: l10n.halloumiSandwichName,
        imagePath: Assets.assetsImagesBr5,
        weight: '',
        calories: 420,
        protein: 28,
        carbs: 34,
        fat: 16,
        ingredients: l10n.halloumiSandwichIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'BR6',
        name: l10n.tunaSandwichName,
        imagePath: Assets.assetsImagesBr6,
        weight: l10n.tunaWeight,
        calories: 425,
        protein: 41,
        carbs: 35,
        fat: 8,
        ingredients: l10n.tunaSandwichIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'BR7',
        name: l10n.fajitasSandwichName,
        imagePath: Assets.assetsImagesBr7,
        weight: l10n.fajitasWeight,
        calories: 470,
        protein: 40,
        carbs: 33,
        fat: 19,
        ingredients: l10n.fajitasSandwichIngredients,
        price: 100,
      ),
    ];
  }

  static List<FoodModel> saladsMeals(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return [
      FoodModel(
        id: 'SLD1',
        name: l10n.bowlOfEggSaladName,
        imagePath: Assets.assetsImagesSld1,
        weight: l10n.eggSaladWeight,
        calories: 325,
        protein: 15,
        carbs: 10,
        fat: 24,
        ingredients: l10n.bowlOfEggSaladIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'SLD2',
        name: l10n.shrimpsCaesarSaladName,
        imagePath: Assets.assetsImagesSld2,
        weight: l10n.shrimpsWeight120g,
        calories: 380,
        protein: 33,
        carbs: 22,
        fat: 15,
        ingredients: l10n.shrimpsCaesarSaladIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'SLD3',
        name: l10n.chickenCaesarSaladName,
        imagePath: Assets.assetsImagesSld3,
        weight: l10n.chickenWeight140g,
        calories: 395,
        protein: 35,
        carbs: 19,
        fat: 15,
        ingredients: l10n.chickenCaesarSaladIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'SLD4',
        name: l10n.crispyChickenSaladName,
        imagePath: Assets.assetsImagesSld4,
        weight: l10n.chickenWeight140g,
        calories: 330,
        protein: 35,
        carbs: 14,
        fat: 12,
        ingredients: l10n.crispyChickenSaladIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'SLD5',
        name: l10n.fetaCheeseSaladName,
        imagePath: Assets.assetsImagesSld5,
        weight: l10n.fetaWeight100g,
        calories: 390,
        protein: 17,
        carbs: 18,
        fat: 27,
        ingredients: l10n.fetaCheeseSaladIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'SLD6',
        name: l10n.tunaSaladName,
        imagePath: Assets.assetsImagesSld6,
        weight: l10n.tunaWeight160g,
        calories: 310,
        protein: 49,
        carbs: 11,
        fat: 6,
        ingredients: l10n.tunaSaladIngredients,
        price: 100,
      ),
    ];
  }

  static List<FoodModel> mainMeals(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    return [
      // الصورة رقم 1
      FoodModel(
        id: 'M1',
        name: l10n.grilledKoftaWithVegName,
        imagePath: Assets.assetsImagesMain1,
        weight: l10n.kofta150g,
        calories: 327,
        protein: 33,
        carbs: 10,
        fat: 30,
        ingredients: l10n.grilledKoftaWithVegIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M2',
        name: l10n.grilledKoftaMealName,
        imagePath: Assets.assetsImagesMain2,
        weight: l10n.koftaRiceMealWeight,
        calories: 442,
        protein: 37,
        carbs: 42,
        fat: 14,
        ingredients: l10n.grilledKoftaMealIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M3',
        name: l10n.grilledChickenMealName,
        imagePath: Assets.assetsImagesMain3,
        weight: l10n.chickenRiceMealWeight,
        calories: 445,
        protein: 35,
        carbs: 40,
        fat: 10,
        ingredients: l10n.grilledChickenMealIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M4',
        name: l10n.chickenKabsaMealName,
        imagePath: Assets.assetsImagesMain4,
        weight: l10n.chickenKabsaWeight,
        calories: 449,
        protein: 39,
        carbs: 42,
        fat: 14,
        ingredients: l10n.chickenKabsaIngredients,
        price: 100,
      ),

      // الصورة رقم 2
      FoodModel(
        id: 'M5',
        name: l10n.chickenCordonBleuName,
        imagePath: Assets.assetsImagesMain5,
        weight: l10n.cordonBleuWeight,
        calories: 452,
        protein: 37,
        carbs: 30,
        fat: 16,
        ingredients: l10n.chickenCordonBleuIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M6',
        name: l10n.chickenBurgerName,
        imagePath: Assets.assetsImagesMain6,
        weight: l10n.chickenBurgerWeight,
        calories: 445,
        protein: 36,
        carbs: 32,
        fat: 16,
        ingredients: l10n.chickenBurgerIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M7',
        name: l10n.chickenCheesePizzaName,
        imagePath: Assets.assetsImagesMain7,
        weight: l10n.pizzaWeight,
        calories: 451,
        protein: 33,
        carbs: 42,
        fat: 17,
        ingredients: l10n.chickenCheesePizzaIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M8',
        name: l10n.mushroomAlfredoPastaName,
        imagePath: Assets.assetsImagesMain8,
        weight: l10n.pastaWeight,
        calories: 432,
        protein: 38,
        carbs: 32,
        fat: 17,
        ingredients: l10n.mushroomAlfredoPastaIngredients,
        price: 100,
      ),

      // الصورة رقم 3
      FoodModel(
        id: 'M9',
        name: l10n.spaghettiBologneseName,
        imagePath: Assets.assetsImagesMain9,
        weight: l10n.spaghettiWeight,
        calories: 474,
        protein: 35,
        carbs: 44,
        fat: 16,
        ingredients: l10n.spaghettiBologneseIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M10',
        name: l10n.chickenLasagnaName,
        imagePath: Assets.assetsImagesMain10,
        weight: l10n.lasagnaWeight120,
        calories: 437,
        protein: 37,
        carbs: 32,
        fat: 18,
        ingredients: l10n.chickenLasagnaIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M11',
        name: l10n.seafoodLasagnaName,
        imagePath: Assets.assetsImagesMain11,
        weight: l10n.seafoodLasagnaWeight,
        calories: 426,
        protein: 34,
        carbs: 32,
        fat: 18,
        ingredients: l10n.seafoodLasagnaIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M12',
        name: l10n.beefLasagnaName,
        imagePath: Assets.assetsImagesMain12,
        weight: l10n.beefLasagnaWeight,
        calories: 455,
        protein: 37,
        carbs: 32,
        fat: 20,
        ingredients: l10n.beefLasagnaIngredients,
        price: 100,
      ),

      // الصورة رقم 4
      FoodModel(
        id: 'M13',
        name: l10n.beefStroganoffMealName,
        imagePath: Assets.assetsImagesMain13,
        weight: l10n.beefStroganoffWeight,
        calories: 480,
        protein: 35,
        carbs: 30,
        fat: 21,
        ingredients: l10n.beefStroganoffIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M14',
        name: l10n.beefSteakPotatoWedgesName,
        imagePath: Assets.assetsImagesMain14,
        weight: l10n.beefSteakWedgesWeight,
        calories: 470,
        protein: 35,
        carbs: 32,
        fat: 19,
        ingredients: l10n.beefSteakWedgesIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M15',
        name: l10n.beefSteakMashedPotatoName,
        imagePath: Assets.assetsImagesMain15,
        weight: l10n.beefSteakMashedWeight,
        calories: 470,
        protein: 35,
        carbs: 32,
        fat: 19,
        ingredients: l10n.beefSteakMashedIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M16',
        name: l10n.beefBallsWithRiceName,
        imagePath: Assets.assetsImagesMain16,
        weight: l10n.beefBallsWeight,
        calories: 440,
        protein: 37,
        carbs: 42,
        fat: 14,
        ingredients: l10n.beefBallsIngredients,
        price: 100,
      ),

      // الصورة رقم 5
      FoodModel(
        id: 'M17',
        name: l10n.grilledFishWithRiceName,
        imagePath: Assets.assetsImagesMain17,
        weight: l10n.grilledFishWeight,
        calories: 449,
        protein: 36,
        carbs: 37,
        fat: 15,
        ingredients: l10n.grilledFishIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M18',
        name: l10n.grilledSalmonWithRiceName,
        imagePath: Assets.assetsImagesMain18,
        weight: l10n.salmonRiceWeight,
        calories: 458,
        protein: 36,
        carbs: 38,
        fat: 18,
        ingredients: l10n.salmonRiceIngredients,
        price: 100,
      ),
      FoodModel(
        id: 'M19',
        name: l10n.grilledSalmonWithVegName,
        imagePath: Assets.assetsImagesMain19,
        weight: l10n.salmonVegWeight,
        calories: 342,
        protein: 34,
        carbs: 10,
        fat: 17,
        ingredients: l10n.salmonVegIngredients,
        price: 100,
      ),
    ];
  }
}
